
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';
export const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const ENTRY_CREATE_SUCCESS = 'ENTRY_CREATE_SUCCESS';
export const ENTRY_CREATE_ERROR = 'ENTRY_CREATE_ERROR';
export const CLEAR_ENTRY_CREATION_STATUS = 'CLEAR_ENTRY_CREATION_STATUS';
export const FETCH_ALL_ENTRIES_SUCCESS = 'FECTCH_ALL_ENTRIES_SUCCESS';
export const FETCH_USER_ENTRIES_SUCCESS = 'FETCH_USER_ENTRIES_SUCCESS';
export const FETCH_TWEETS_SUCCESS = 'FETCH_TWEETS_SUCCESS';
export const TWEET_HIDDEN_SUCCESSFULY = 'TWEET_HIDDEN_SUCCESSFULY';
export const CLEAR_HIDE_ACTION = 'CLEAR_HIDE_ACTION';
export const TWEET_SHOWN_SUCCESSFULY = 'TWEET_SHOWN_SUCCESSFULY';
